import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
const fails = [];
p.on('pageerror', e => fails.push('JS ERROR: ' + e.message));
p.on('console', m => { if (m.type() === 'error') fails.push('CONSOLE: ' + m.text()); });
p.on('response', r => { if (r.status() >= 400) fails.push(`HTTP ${r.status()} ${r.url()}`); });
await p.goto('https://felxmodaso-collab.github.io/ostov-cyclework/?cb=' + Date.now(), { waitUntil: 'networkidle', timeout: 60000 });
await p.waitForTimeout(2500);
await p.screenshot({ path: '_check_top.png' });
console.log('FAILS:', fails.length);
fails.forEach(f => console.log('  ' + f));
await b.close();
